# Host to use for canonical URL generation (without trailing slash)
host: https://dfe-digital.github.io/continuing-professional-development-developer-docs

# Header-related options
show_govuk_logo: false
service_name: Manage
service_link: https://api-continuing-professional-development.education.gov.uk

# Links to show on right-hand-side of header
header_links:
  Documentation: /
  GitHub: https://github.com/DFE-Digital/continuing-professional-development-api

footer_links:
  About: /
  Accessibility: /accessibility.html
  Support: /support.html

# Enables search functionality. This indexes pages only and is not recommended for single-page sites.
enable_search: true

# Tracking ID from Google Analytics (e.g. UA-XXXX-Y)
ga_tracking_id:

# Enable multipage navigation in the sidebar
multipage_nav: true

# Enable collapsible navigation in the sidebar
collapsible_nav: true

# Table of contents depth – how many levels to include in the table of contents.
# If your ToC is too long, reduce this number and we'll only show higher-level
# headings.
max_toc_heading_level: 2

# Prevent robots from indexing (e.g. whilst in development)
prevent_indexing: true

show_contribution_banner: false
github_repo: DFE-Digital/continuing-professional-development-developer-docs
github_branch: main

open_api_path: ../swagger/v1/api_spec.json
